//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayoutDistribution
    {
        public long ID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> SponsorID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> MainCustomerID { get; set; }
    }
}
