//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public long VariantID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<decimal> AdditionalPrice { get; set; }
        public Nullable<int> Stock { get; set; }
        public string SKU { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    }
}
