//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Wallet
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string TransitionAmount { get; set; }
        public string TransitionTypes { get; set; }
        public string TransitionDate { get; set; }
        public string TransitionStatus { get; set; }
        public Nullable<long> MemberID { get; set; }
    }
}
