//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public long Id { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public string AddressType { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string AlternatePhone { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
