//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrandMaster
    {
        public long BrandID { get; set; }
        public string Brand_Name { get; set; }
        public string Brand_Image { get; set; }
        public string Brand_Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
