//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerAadharCard
    {
        public long ID { get; set; }
        public string AadharNumder { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string AadharFrontImage { get; set; }
        public string AadharBankImage { get; set; }
        public string Status { get; set; }
        public string DateTime { get; set; }
    }
}
