//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public long CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerImage { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<long> CustomerPhone { get; set; }
        public Nullable<long> CustomerZIP { get; set; }
        public Nullable<long> StateID { get; set; }
        public Nullable<long> CityID { get; set; }
        public string CustomerLandmark { get; set; }
        public string CustomerPointValue { get; set; }
        public string Status { get; set; }
        public string Customer_Gender { get; set; }
        public Nullable<long> UserID { get; set; }
        public string DOB { get; set; }
        public Nullable<double> pvvlaue { get; set; }
        public Nullable<long> SponserID { get; set; }
        public string Position { get; set; }
    }
}
