//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCityMaster
    {
        public long CityID { get; set; }
        public string City_Name { get; set; }
        public string City_Status { get; set; }
        public Nullable<long> DistrictID { get; set; }
        public Nullable<long> PinCode { get; set; }
    }
}
