//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerBankDetail
    {
        public long Id { get; set; }
        public long CustomerID { get; set; }
        public string FullName { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCcode { get; set; }
        public string BranchName { get; set; }
        public string Status { get; set; }
        public Nullable<long> BankID { get; set; }
    }
}
