//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        public long CartID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> SizeID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> TotalPice { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public Nullable<long> VarientId { get; set; }
    }
}
