//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryMaster
    {
        public long CategoryID { get; set; }
        public string Category_Name { get; set; }
        public string Category_Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CategoryImage { get; set; }
    }
}
