//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDummyCustdata
    {
        public long id { get; set; }
        public string ZEDPLUSID { get; set; }
        public string Name { get; set; }
        public string superzedplusid { get; set; }
        public string mobileno { get; set; }
    }
}
