//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrievance
    {
        public long ID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DocumentPath { get; set; }
        public string EntryDateTime { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
