//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemMaster
    {
        public long ItemID { get; set; }
        public string Item_Name { get; set; }
        public string Item_Image { get; set; }
        public string Item_Status { get; set; }
        public string Item_Price { get; set; }
        public string Item_Detail { get; set; }
        public Nullable<long> BrandID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> SubCategoryID { get; set; }
        public Nullable<long> SubMenuID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Item_PointValue { get; set; }
        public string Item_Qty { get; set; }
        public string Item_Cost { get; set; }
        public string Item_Discount { get; set; }
        public string Item_Sizes { get; set; }
        public string Item_Color { get; set; }
        public Nullable<double> MemberPrice { get; set; }
    }
}
