//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntroducerIncome
    {
        public long ID { get; set; }
        public Nullable<long> CID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public string Amount { get; set; }
    }
}
