//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntroducer
    {
        public long ID { get; set; }
        public string Introducer_Name { get; set; }
        public string Introducer_Email { get; set; }
        public string Introducer_Mobile { get; set; }
        public string Introducer_Address { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public long CustomerID { get; set; }
        public Nullable<long> StateID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> District { get; set; }
        public string PinCode { get; set; }
        public string Gender { get; set; }
        public string FatherName { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<long> SponsorID { get; set; }
        public Nullable<long> PraposerID { get; set; }
        public string Introducer_Image { get; set; }
    }
}
