//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMOQmaster
    {
        public long ID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> MOQQuantity { get; set; }
        public string EffectiveDate { get; set; }
        public string EntryDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> StoreTypeID { get; set; }
    }
}
