//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeetingSchedule
    {
        public long ID { get; set; }
        public string MeetingDate { get; set; }
        public string MeetingCity { get; set; }
        public string Location { get; set; }
        public string Timing { get; set; }
        public string EntryDate { get; set; }
        public string Status { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}
