//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public long OrderID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> Itemid { get; set; }
        public Nullable<long> VaraintsID { get; set; }
        public long TotalPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TotalPV { get; set; }
        public Nullable<long> AddressId { get; set; }
        public string OrderNumber { get; set; }
        public string PaymentStatus { get; set; }
    }
}
