//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public long ID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> SubcategoryID { get; set; }
        public Nullable<long> SubMenuID { get; set; }
        public string Item_Name { get; set; }
        public Nullable<long> Stock { get; set; }
        public string UnitValue { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> QuantityperCarton { get; set; }
        public Nullable<double> MRP { get; set; }
        public string BasicDiscountType { get; set; }
        public Nullable<double> BasicDiscount { get; set; }
        public Nullable<double> NRP { get; set; }
        public string MemberDiscountType { get; set; }
        public Nullable<double> MemberDiscount { get; set; }
        public Nullable<double> DP { get; set; }
        public string PV { get; set; }
        public Nullable<double> GST { get; set; }
        public string BARCODE { get; set; }
        public string FranchiseType { get; set; }
        public Nullable<double> FranchiseDiscountValue { get; set; }
        public Nullable<double> FranchiseCommission { get; set; }
        public string ManagementType { get; set; }
        public Nullable<double> ManagementDiscountValue { get; set; }
        public Nullable<double> ManagementCommission { get; set; }
        public string Description { get; set; }
        public string DistributionType { get; set; }
        public Nullable<double> DistributionDiscountValue { get; set; }
        public Nullable<double> DistributionCommission { get; set; }
        public string OtherType { get; set; }
        public Nullable<double> OtherDiscountValue { get; set; }
        public Nullable<double> OtherCommission { get; set; }
        public string Status { get; set; }
        public string Date { get; set; }
        public Nullable<long> BrandID { get; set; }
        public Nullable<long> PackingID { get; set; }
        public Nullable<long> HsnCode { get; set; }
    }
}
