//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductTransfer
    {
        public long ID { get; set; }
        public Nullable<long> source_storeID { get; set; }
        public Nullable<long> destination_storeID { get; set; }
        public Nullable<long> Product_id { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> QuantityperCarton { get; set; }
        public Nullable<long> StockQTY { get; set; }
        public string transfer_date { get; set; }
        public string status { get; set; }
    }
}
