//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproductinfo
    {
        public long ID { get; set; }
        public long ProductID { get; set; }
        public string GTIN { get; set; }
        public string ProductOrigin { get; set; }
        public string ManufacturerName { get; set; }
        public string WarrantyPeriod { get; set; }
        public string NetWeight { get; set; }
        public string NetContent { get; set; }
        public string GrossWeight { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> ReturnPolicy { get; set; }
        public string SKU { get; set; }
    }
}
