//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public long PaymentID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string PaymentDate { get; set; }
        public string PaymentMethod { get; set; }
    }
}
