//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchase
    {
        public long ID { get; set; }
        public string ClientBillNo { get; set; }
        public string Date { get; set; }
        public Nullable<long> VenderID { get; set; }
        public Nullable<long> SubMenuID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<double> QtyperUnit { get; set; }
        public Nullable<double> StockQuantity { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> GstRate { get; set; }
        public Nullable<double> GstAmount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<long> BrandID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> SubCategoryID { get; set; }
        public string Status { get; set; }
        public Nullable<long> StoreID { get; set; }
        public Nullable<long> StoreTypeID { get; set; }
    }
}
