//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQty
    {
        public long QuantityID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> SubCategoryID { get; set; }
        public string Unit { get; set; }
    }
}
