//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceiveProduct
    {
        public long ID { get; set; }
        public string Source_storeID { get; set; }
        public string Destination_storeID { get; set; }
        public string Product_id { get; set; }
        public string Quantity { get; set; }
        public string UnitID { get; set; }
        public string QuantityperCarton { get; set; }
        public string StockQTY { get; set; }
        public string Receive_date { get; set; }
        public string Received_from { get; set; }
        public string Transfer_id { get; set; }
        public string Status { get; set; }
    }
}
