//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubCategoryMaster
    {
        public long SubCategoryID { get; set; }
        public string SubCategory_Name { get; set; }
        public string SubCategory_Status { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ImagePath { get; set; }
    }
}
