//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipping
    {
        public long ShippingID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string ShippingStatus { get; set; }
        public string TrackingNumber { get; set; }
        public string EstimatedDeliveryDate { get; set; }
        public string ShippingDate { get; set; }
        public string DeliveryDate { get; set; }
    }
}
