//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStore_Master
    {
        public long StoreID { get; set; }
        public string Store_Name { get; set; }
        public string Store_Address { get; set; }
        public string Store_Status { get; set; }
        public Nullable<long> Store_Type { get; set; }
        public string Date { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> StateID { get; set; }
        public Nullable<long> DistrictID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> PinCode { get; set; }
        public string Store_Email { get; set; }
        public string Store_Phone { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Person_Name { get; set; }
    }
}
