//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockEntry
    {
        public long ID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public string UnitValue { get; set; }
        public Nullable<long> UnitID { get; set; }
        public string QtyperCartoon { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<double> NRP { get; set; }
        public Nullable<double> DP { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<long> HSN { get; set; }
        public string BARCODE { get; set; }
        public string Status { get; set; }
        public Nullable<long> CoupenID { get; set; }
        public string EntryDate { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<long> VariantID1 { get; set; }
        public Nullable<long> VariantValueID1 { get; set; }
        public Nullable<long> VariantID2 { get; set; }
        public Nullable<long> VariantValueID2 { get; set; }
        public Nullable<long> VariantID3 { get; set; }
        public Nullable<long> VariantValueID3 { get; set; }
        public Nullable<long> VariantID4 { get; set; }
        public Nullable<long> VariantValueID4 { get; set; }
        public Nullable<long> VariantID5 { get; set; }
        public Nullable<long> VariantValueID5 { get; set; }
        public Nullable<long> VariantID6 { get; set; }
        public Nullable<long> VariantValueID6 { get; set; }
        public string ModifiedDate { get; set; }
    }
}
