//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStateMaster
    {
        public long StateID { get; set; }
        public string State_Name { get; set; }
        public string State_Status { get; set; }
        public Nullable<long> Country_ID { get; set; }
    }
}
