//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVenderMaster
    {
        public long ID { get; set; }
        public string Vender_Name { get; set; }
        public string Vender_Email { get; set; }
        public string Vender_Mobile { get; set; }
        public string Vender_Address { get; set; }
        public string VenderGST_no { get; set; }
        public string Vender_Pincode { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> StateID { get; set; }
        public Nullable<long> DistrictID { get; set; }
        public Nullable<long> CityID { get; set; }
    }
}
