//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedPlusAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantAttributeValue
    {
        public int ID { get; set; }
        public Nullable<int> VariantID { get; set; }
        public Nullable<int> AttributeID { get; set; }
        public Nullable<int> AttributeValueID { get; set; }
    }
}
